spring:
  profiles:
    active: local
  cache:
    caffeine:
      zones: maximumSize=1, expireAfterWrite=10s
      time: maximumSize=2, expireAfterWrite=3s
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 80
